### PR TITLE
Sort joined output

### PR DESCRIPTION
**Pull request by supersonicclay**
When using `-j`, sort the output.

### CODE REVIEW

**Comment by bahamas10** [comment]
thanks! This will sort based on the command output, and not the hostnames... is this what you expect?

For example, before

```$ sshp -f /opt/custom/etc/cheffable -j uname -v
[sshp] finished 22/22

finished with 5 unique results

hosts (12/22): arbiter build cifs datadyne jabber nagios ns2 ops qseer tftp vault vpn
joyent_20171110T033222Z

hosts (3/22): btsync plex vulture
BrandZ virtual linux

hosts (4/22): dhcp nat ns1 portal
joyent_20171012T151912Z

hosts (2/22): garage-pi mirror-pi
#977 SMP Mon Mar 13 18:25:19 GMT 2017

hosts (1/22): gz
joyent_20171121T004858Z

```

After

```
$ ./sshp.js -f /opt/custom/etc/cheffable -j uname -v
[sshp] finished 22/22

finished with 5 unique results

hosts (2/22): garage-pi mirror-pi
#977 SMP Mon Mar 13 18:25:19 GMT 2017

hosts (3/22): btsync plex vulture
BrandZ virtual linux

hosts (4/22): dhcp nat ns1 portal
joyent_20171012T151912Z

hosts (12/22): arbiter build cifs datadyne jabber nagios ns2 ops qseer tftp vault vpn
joyent_20171110T033222Z

hosts (1/22): gz
joyent_20171121T004858Z

```

Notice that the output is sorted by `stdout` itself.

**Comment by claycephas** [comment]
Yes. At least for my use case, I was interested in the unique set of outputs more than I was the hostnames. Since there are multiple hostnames, I don't know that it makes sense to sort on one of the hostnames.

**Comment by bahamas10** [comment]
sounds good to me! and yeah, sorting based on the first hostname in a list really doesn't do much since multiple hostnames that follow the first one could have any other name without any sorting.

**Comment by bahamas10** [comment]
Thanks!

```
$ npm publish
+ sshp@0.4.5
```

**Pull request merged**
